### ISSUE TITLE
No error for invalid sourcemap

### ISSUE THREAD

**Issue by timbell** [lydell/source-map-resolve#10]
Hi,

No error is reported if resolve is called with a (presumably invalid) sourcemap containing no sources entries:
```
{"version":3,"sources":[],"names":[],"mappings":"","file":"foo.js","sourceRoot":"","sourcesContent":[]}
```
There are bugs in [source-map](https://github.com/mozilla/source-map/issues/250) that cause such sourcemaps to be produced.

I think the problem is in [resolveSourcesHelper](https://github.com/lydell/source-map-resolve/blob/663ad74f07aab1d5ef44942fd9c4df91cee5e687/lib/source-map-resolve-node.js#L171) as the case where sources.length === 0 is not handled.

**Comment by lydell** [comment]
Could you explain what your problem is? I'm not sure it is source-map-resolve's job to validate this.

**Comment by timbell** [comment]
As I understand it, when using `resolve` success/failure is signalled by a call to the passed callback. When a sourcemap with an empty sources array is passed the callback is not called. The context I saw this in was using rollup and rollup-plugin-sourcemaps. I have sourcemaps with empty sources arrays (see this [bug](https://github.com/mozilla/source-map/issues/250)) and they cause rollup to exit silently producing no output.

I think `resolve` should always call the callback otherwise callers will break with unpredictable results. For example, something like the following could be done in `resolveSources` before the call to `resolveSourcesHelper`:

```
if (!map.sources.length) {
  callback(new Error('Invalid sourcemap - empty sources array'));
} 
```

**Comment by lydell** [comment]
Good point about the the callback not being called. You are correct that the callback should always be called.

Things that need to be done:

- Decide if an empty sources array should be an error or return an empty result.
- Make sure that all exposed async functions always call their callback.
- Make sure that the sync versions are consistent.
- Add tests for all functions.

Do you want to make a PR? (Be warned that this code base is pretty old and unpleasant to work with, but it shouldn't be too hard.)
