### ISSUE TITLE
Garbled characters appear when sourcesContent contains Chinese characters

### ISSUE THREAD

**Issue by xiaoxiangmoe** [lydell/source-map-resolve#13]
https://github.com/lydell/source-map-resolve/blob/858cd9e2ecce25427761b8be616cabf704c69316/lib/source-map-resolve-node.js#L101

`atob` equals
```js
const atob = (encodedString) => Buffer.from(encodedString, 'base64').toString('latin1')
```

But we should use utf-8 rather than binary:
```js
(encodedString) => Buffer.from(encodedString, 'base64').toString()
// or
(encodedString) => Buffer.from(encodedString, 'base64').toString('utf8')
```

see https://github.com/ng-packagr/ng-packagr/issues/1475

I can take a pr later to solve the character set problem.

**Comment by lydell** [comment]
Thanks for reporting and fixing this! Released in v0.5.3.
