### ISSUE TITLE
make this a standalone ./bin tool

### ISSUE THREAD

**Issue by Masterxilo** [lydell/source-map-resolve#23]
I want to be able to use this as follows:

```
npm install -g source-map-resolve
source-map-resolve file.js
```

thanks

**Comment by lydell** [comment]
Hi!

I won’t add a CLI in this repo, because I don’t need it myself and I don’t want to maintain it.

Maybe this one is good? https://www.npmjs.com/package/source-map-cli?activeTab=dependencies

If you end up making a CLI yourself, feel free to post here so I can link to it!
