### ISSUE TITLE
source-map-resolve appears to depend on depreciated packages

### ISSUE THREAD

**Issue by adamcooper1386** [lydell/source-map-resolve#27]
<img width="1268" alt="Screen Shot 2021-05-12 at 8 10 58 PM" src="https://user-images.githubusercontent.com/38062975/118072301-5805b980-b35e-11eb-82fa-c9e991053bfc.png">

Did a fresh install of @jest/transform using yarn and got two depreciation warning both coming from this package. I'll similarly post there.

**Comment by lydell** [comment]
Hi! Why don’t you follow the links in the screen shot you posted and read what’s there?

**Comment by adamcooper1386** [comment]
I'm sorry, I guess I wasn't clear. I'm not the maintainer of any of the packages listed in the warning. I can't just make source-map-resolve not depend on resolve-url on my own without forking a ton of projects and maintaining my own version. And not using babel-jest because source-map-resolve depends on a now deprecated packages seems like an extreme solution to a small problem. I was trying to be helpful and let the appropriate project owners know that the warnings are there.
