### ISSUE TITLE
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated

### ISSUE THREAD

**Issue by rodoabad** [lydell/source-map-resolve#33]
`source-map-resolve` is throwing an NPM warning for `urix`.

```
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
```

**Comment by lydell** [comment]
That is correct. The link you posted explains. And as you might have noticed, I’m the author of both urix and source-map-resolve, so it is me who deprecated urix etc.
