### ISSUE TITLE
decode-uri-component <= 0.2.0 DoS

### ISSUE THREAD

**Issue by elcreator** [lydell/source-map-resolve#36]
https://github.com/advisories/GHSA-w573-4hg7-7wgq

**Comment by elcreator** [comment]
https://www.npmjs.com/package/snapdragon depends on this

**Comment by lydell** [comment]
This package is deprecated.

snapdragon is unmaintained.

Here’s how to get rid of it (most likely): https://github.com/lydell/source-map-resolve#deprecated
